# Generated by Django 3.2.25 on 2025-06-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderLineItem',
            new_name='OrderLineItem',
        ),
    ]
