# Generated by Django 3.2.25 on 2025-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250318_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
